[2024-07-02T15:24:39.151+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline.check_load manual__2024-07-02T15:24:32.726421+00:00 [queued]>
[2024-07-02T15:24:39.160+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline.check_load manual__2024-07-02T15:24:32.726421+00:00 [queued]>
[2024-07-02T15:24:39.160+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2024-07-02T15:24:39.172+0000] {taskinstance.py:2192} INFO - Executing <Task(_PythonExternalDecoratedOperator): check_load> on 2024-07-02 15:24:32.726421+00:00
[2024-07-02T15:24:39.178+0000] {standard_task_runner.py:60} INFO - Started process 1083 to run task
[2024-07-02T15:24:39.181+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'pipeline', 'check_load', 'manual__2024-07-02T15:24:32.726421+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmp08xg1eek']
[2024-07-02T15:24:39.183+0000] {standard_task_runner.py:88} INFO - Job 16: Subtask check_load
[2024-07-02T15:24:39.226+0000] {task_command.py:423} INFO - Running <TaskInstance: pipeline.check_load manual__2024-07-02T15:24:32.726421+00:00 [running]> on host e21b7712e0d7
[2024-07-02T15:24:39.289+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pipeline' AIRFLOW_CTX_TASK_ID='check_load' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T15:24:32.726421+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-02T15:24:32.726421+00:00'
[2024-07-02T15:24:39.332+0000] {python.py:903} WARNING - When checking for Airflow installed in virtual environment got Command '['/opt/airflow/soda_venv/bin/python', '-c', 'from airflow import __version__; print(__version__)']' returned non-zero exit status 1.
[2024-07-02T15:24:39.334+0000] {python.py:904} WARNING - This means that Airflow is not properly installed by  /opt/***/soda_venv/bin/python. Airflow context keys will not be available. Please Install Airflow 2.8.0 in your environment to access them.
[2024-07-02T15:24:39.540+0000] {process_utils.py:182} INFO - Executing cmd: /opt/***/soda_venv/bin/python /tmp/venv-callh6rbdf5z/script.py /tmp/venv-callh6rbdf5z/script.in /tmp/venv-callh6rbdf5z/script.out /tmp/venv-callh6rbdf5z/string_args.txt /tmp/venv-callh6rbdf5z/termination.log
[2024-07-02T15:24:39.551+0000] {process_utils.py:186} INFO - Output:
[2024-07-02T15:24:42.803+0000] {process_utils.py:190} INFO - Running Soda Scan ...
[2024-07-02T15:24:42.804+0000] {process_utils.py:190} INFO - INFO   | Soda Core 3.0.45
[2024-07-02T15:24:42.805+0000] {process_utils.py:190} INFO - DEBUG  | Reading configuration file "/opt/***/dossier/soda/configuration/configuration.yml"
[2024-07-02T15:24:42.805+0000] {process_utils.py:190} INFO - DEBUG  | Reading SodaCL file "/opt/***/dossier/soda/checks//premier_checks.yml"
[2024-07-02T15:24:42.806+0000] {process_utils.py:190} INFO - DEBUG  | Scan execution starts
[2024-07-02T15:24:42.807+0000] {process_utils.py:190} INFO - DEBUG  | Postgres connection properties: host="postgres", port="None", database="***", user="***", options="-c search_path=public", connection_timeout="None"
[2024-07-02T15:24:42.808+0000] {process_utils.py:190} INFO - DEBUG  | Query bdpostgres.products.schema[products]:
[2024-07-02T15:24:42.809+0000] {process_utils.py:190} INFO - SELECT column_name, data_type, is_nullable
[2024-07-02T15:24:42.810+0000] {process_utils.py:190} INFO - FROM information_schema.columns
[2024-07-02T15:24:42.810+0000] {process_utils.py:190} INFO - WHERE lower(table_name) = 'products'
[2024-07-02T15:24:42.811+0000] {process_utils.py:190} INFO -   AND lower(table_catalog) = '***'
[2024-07-02T15:24:42.811+0000] {process_utils.py:190} INFO -   AND lower(table_schema) = 'public'
[2024-07-02T15:24:42.812+0000] {process_utils.py:190} INFO - ORDER BY ORDINAL_POSITION
[2024-07-02T15:24:42.812+0000] {process_utils.py:190} INFO - INFO   | Scan summary:
[2024-07-02T15:24:42.813+0000] {process_utils.py:190} INFO - DEBUG  | 1/1 query OK
[2024-07-02T15:24:42.813+0000] {process_utils.py:190} INFO - DEBUG  |   bdpostgres.products.schema[products] [OK] 0:00:00.007931
[2024-07-02T15:24:42.814+0000] {process_utils.py:190} INFO - INFO   | 1/1 check PASSED:
[2024-07-02T15:24:42.814+0000] {process_utils.py:190} INFO - INFO   |     products in bdpostgres
[2024-07-02T15:24:42.815+0000] {process_utils.py:190} INFO - INFO   |       Schema Check [/opt/***/dossier/soda/checks//premier_checks.yml] [PASSED]
[2024-07-02T15:24:42.815+0000] {process_utils.py:190} INFO - INFO   |         schema_measured = [invoiceno text, stockcode text, description text, quantity integer, invoicedate timestamp without time zone, unitprice real, customerid real, country text]
[2024-07-02T15:24:42.816+0000] {process_utils.py:190} INFO - INFO   | All is good. No failures. No warnings. No errors.
[2024-07-02T15:24:42.816+0000] {process_utils.py:190} INFO - INFO   | Sending results to Soda Cloud
[2024-07-02T15:24:42.816+0000] {process_utils.py:190} INFO - INFO   | Soda Cloud Trace: 7963670067997399281
[2024-07-02T15:24:42.862+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-07-02T15:24:42.873+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=pipeline, task_id=check_load, execution_date=20240702T152432, start_date=20240702T152439, end_date=20240702T152442
[2024-07-02T15:24:42.927+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-07-02T15:24:42.989+0000] {taskinstance.py:3281} INFO - 1 downstream tasks scheduled from follow-on schedule check
